logging:
  config: 'classpath:log4j2.yml'

spring:
  application:
    name: marketplace-migration
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

app:
  database:
    dev:
      url: jdbc:postgresql://mp-db-dev:5432/mp_db_dev
      username: mp_dev_user
      password: mp_dev_passwd
      driver-class-name: org.postgresql.Driver

server:
  port: 33300
